---
title: "assing-test"
description: |
  A short description of the post.
author:
  - name: DONG Fang (Regina)
    url: https://www.linkedin.com/in/reginadongf/
    affiliation: School of Computing and Information Systems, Singapore Management University
    affiliation_url: https://scis.smu.edu.sg/
date: 07-17-2021
output:
  distill::distill_article:
    self_contained: false
    toc: True
    toc_depth: 5
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.retina = 3,   # To make the figure looks sharper, set the retina value >=3, default is 1 
                      echo = TRUE,      # Show code chunk
                      eval = TRUE,      # Run the code
                      message = FALSE,  # Don't show error massage
                      warning = FALSE)  # Don't show warning massage
```

Launch packages

```{r}
packages = c('ggiraph', 'plotly','DT', 'patchwork', 
             'raster', 'sf','tmap', 'mapview','gifski',
             'tidyverse', 'mlr','lubridate')
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```

Import data

```{r}
car_ass <- read_csv("data/car-assignments.csv")
gps <- read_csv("data/gps.csv")
cc <- read_csv("data/cc_data.csv", locale = locale(encoding = "windows-1252"))
loyalty <- read_csv("data/loyalty_data.csv", locale = locale(encoding = "windows-1252"))

gps$Timestamp = mdy_hms(gps$Timestamp)
cc$timestamp = mdy_hm(cc$timestamp)
loyalty$timestamp = mdy(loyalty$timestamp)

car_ass$CarID = as.character(car_ass$CarID)
gps$id = as.character(gps$id)
cc$last4ccnum = as.character(cc$last4ccnum)

cc$day = day(cc$timestamp)
cc$hour = hour(cc$timestamp)
loyalty$day = day(loyalty$timestamp)
gps$day = as.factor(day(gps$Timestamp))
gps$hour = as.factor(hour(gps$Timestamp))
```

Interactive plot

```{r}
d <- highlight_key(cc)

gra_1 <- plot_ly(data = d, x = ~as.factor(hour), y = ~location,
                 hovertemplate = paste(
                   " %{yaxis.title.text}: %{y}<br>",
                   "%{xaxis.title.text}: %{x}<br>",
                   "Transaction Count: %{z}",
                   "<extra></extra>")) %>%
  add_histogram2d(colors = "Blues") %>%
  layout(title = "<b>Graph.1 Credit Card Transcation Frequency by Hour</b>",
         xaxis = list(title = "Time", tickmode = "linear"),
         yaxis = list(title="Location", tickmode = "linear")
         )

crosstalk::bscols(gra_1,
                  crosstalk::filter_select("day", "Day", d, ~as.factor(day), multiple = F), widths = 10)
```


Map

```{r}
gra_2.1 <- plot_ly(data = cc, x = ~as.factor(day), y = ~location,
                 hovertemplate = paste(
                   " %{yaxis.title.text}: %{y}<br>",
                   "%{xaxis.title.text}: %{x}<br>",
                   "Transaction Count: %{z}",
                   "<extra></extra>")) %>%
  add_histogram2d(colors = "Blues") %>%
  layout(annotations = list(text = "Credit Card", showarrow = F, x =10, y=32),
         xaxis = list(tickmode = "linear"),
         yaxis = list(tickmode = "linear")
         )

gra_2.2 <- plot_ly(data = loyalty, x = ~as.factor(day), y = ~location,
                 hovertemplate = paste(
                   " Location: %{y}<br>",
                   "Date of Jan: %{x}<br>",
                   "Transaction Count: %{z}",
                   "<extra></extra>")) %>%
  add_histogram2d(colors = "Purples") %>%
  layout(annotations = list(text = "Loyalty Card", showarrow = F, x =10, y=32),
         xaxis = list(tickmode = "linear"),
         yaxis = list(tickmode = "linear", visible = T)
         )

gra_2 <- subplot(gra_2.1, gra_2.2, nrows = 1, shareY = T) %>%
  layout(title = "<b>Graph.2 Transaction Frequency by Day</b>",
         xaxis = list(title = "Date of Jan"),
         xaxis2 = list(title = "Date of Jan"),
         yaxis = list(title = "Location"),
         autosize = F, width = 900, width2 = 900, height = 400
         )

gra_2
```

geo map

```{r}
bgmap <- raster("data/Geospatial/MC2-tourist.tif")

tm_shape(bgmap) +
tm_rgb(bgmap, r = 1,g = 2,b = 3,
       alpha = NA,
       saturation = 1,
       interpolate = TRUE,
       max.value = 255)

Abila_st <- st_read(dsn = "data/Geospatial",layer = "Abila")

gps_sf <- st_as_sf(gps, 
                   coords = c("long", "lat"),
                   crs = 4326)

# Group by id and day
gps_path <- gps_sf %>%
  group_by(id, day) %>%
  summarize(m = mean(Timestamp), 
            do_union=FALSE) %>%
  st_cast("LINESTRING")

np = npts(gps_path, by_feature = T)
gps_path2 <- cbind(gps_path, np) %>%
  filter(np > 1) # exclude orphan coordinate records

# Group by day and hour
gps_hour <- gps_sf %>%
  group_by(day, hour) %>%
  summarise(m = mean(Timestamp),
            do_union = FALSE) %>%
  st_cast("LINESTRING")

```


```{r}
tmap_mode("view")

m <- tm_shape(bgmap) +
  tm_rgb(bgmap, r = 1,g = 2,b = 3,
       alpha = NA,
       saturation = 1,
       interpolate = TRUE,
       max.value = 255) +
  tm_shape(gps_path2) +
  tm_lines(col = "day") 
  #tm_facets(by = "id")
m
```



